---
- include_tasks: download_prep.yml
  when:
    - not skip_downloads|default(false)

- name: "Download items"
  include_tasks: "download_{% if download.container %}container{% else %}file{% endif %}.yml"
  vars:
    download: "{{ download_defaults | combine(item.value) }}"
  with_dict: "{{ downloads }}"
  when:
    - not skip_downloads|default(false)
    - item.value.enabled

- name: "archive docker images"
  command: "{{ docker_bin_dir }}/docker save -o {{ local_save_directory }}/{{ item.value.repo | replace('/', '_') }}:{{item.value.tag}}.tar {{item.value.repo}}:{{item.value.tag}}"
  vars:
    download: "{{ download_defaults | combine( item.value ) }}"
  with_dict: "{{ downloads }}"
  when: 
    - archive_images
    - not skip_downloads|default(false)
    - item.value.enabled


- name: "Sync container"
  include_tasks: sync_container.yml
  vars:
    download: "{{ download_defaults | combine(item.value) }}"
  with_dict: "{{ downloads }}"
  when:
    - not skip_downloads|default(false)
    - item.value.enabled
    - item.value.container
    - download_run_once
    - group_names | intersect(download.groups) | length
